### ISSUE TITLE
DRBD ressources not demoted to Secondary on service stop

### ISSUE THREAD

**Issue by Phoenixoboros** [opensvc/opensvc#151]
Hello,

DRBD ressources are not passed "Secondary" on service stop, this causes other nodes to not be able to promote the DRBD ressources to "Primary" in a Primary/Secondary DRBD setup.

I am running:
**opensvc-2.1-2.noarch
drbd-9.11.0-1.el7.x86_64**
drbd-bash-completion-9.11.0-1.el7.x86_64
drbd-debuginfo-9.11.0-1.el7.x86_64
drbd-heartbeat-9.11.0-1.el7.x86_64
drbd-kernel-debuginfo-9.0.21-1.x86_64
drbd-man-ja-9.11.0-1.el7.x86_64
drbd-pacemaker-9.11.0-1.el7.x86_64
drbd-udev-9.11.0-1.el7.x86_64
drbd-utils-9.11.0-1.el7.x86_64
drbd-xen-9.11.0-1.el7.x86_64
**kmod-drbd-9.0.21_3.10.0_862.14.4.el7.x86_64-1.x86_64**

Regards,

**Comment by cvaroqui** [comment]
Hi,

drbd resources must be configured with standby=true.
I'll check docs.opensvc.com and make sure this is clearly stated.

Thanks.

**Comment by cvaroqui** [comment]
This issue is related to #150 
The discussion can go on there.
