### ISSUE TITLE
Fix concurrent cluster join

### ISSUE THREAD

**Issue by arnaudveron** [opensvc/opensvc#20]
When multiple nodes join cluster in // we end up with failed cluster build

Exemple : node2/3/4 are joining simultaneously node1
Result : 
```
root@node1:~# om cluster get --kw cluster.nodes
node1 node4
root@node1:~# ssh node2 om cluster get --kw cluster.nodes
node1 node2
root@node1:~# ssh node3 om cluster get --kw cluster.nodes
node1 node3
root@node1:~# ssh node4 om cluster get --kw cluster.nodes
node1 node4
``

**Comment by cvaroqui** [comment]
Fixed by:

d684d3fbfc9a370cb657c5e2c1e780255c044d8a
c09ac4238889f894681f7808792e8b28833df4b8
34ceb90471625f9bab6585ff3ab6ff80c2ef2c1f
