### ISSUE TITLE
custom SSH port

### ISSUE THREAD

**Issue by alucionet** [opensvc/opensvc#406]
Hello,

Is there a way to use different SSH port (not 22) with OpenSVC?
It impacts rsync, etc that relies on the ssh service.

Thanks

**Comment by cvaroqui** [comment]
Hello,
Unfortunately, this feature is not supported.

Changing the "rsh" definition in env.py could be enough, at least for the sync.rsync driver, but this file is not a configuration file, so your change would be overriden upon opensvc upgrade.

Supporting a per-node non-default ssh port would sure be interesting, but our R&D hands are quite full already. Is there is business motivation we should consider to prioritize that dev, or can you consider contributing it ?

Best regards,
Christophe.

**Comment by arnaudveron** [comment]
Hello,

As a workaround, we can suggest using a ssh client configuration on both nodes, in the `/root/.ssh/config` file

```
Host node1
   HostName node1.acme.com
   Port 12345
   User root
   StrictHostKeyChecking no
Host node2
   HostName node2.acme.com
   Port 54321
   User root
   StrictHostKeyChecking no
```

Tip: the `om node update ssh authorized keys` can help to distribute ssh public keys to remote nodes
