### ISSUE TITLE
What is the license of this repository?

### ISSUE THREAD

**Issue by bzg** [opensvc/opensvc#563]
Hi, I've found [a reference to GPL-2.0 in this page of the documentation](https://docs.opensvc.com/latest/introduction.html), but I'm not sure it covers this repository.

Would it be okay to add a LICENSE file to this repository (and others, if needed)?

I'd also suggest to use [GPL-2.0+](https://spdx.org/licenses/GPL-2.0-or-later.html) (the "or later" variant).

What do you think?

**Comment by cvaroqui** [comment]
Thank you for raising this up.
The #564 PR  has fixed this issue.
We kept the original license, but the next major release may ship with a more open license.
Over the next few weeks, we will also add a LICENSE file to the other opensvc github projects.

Thank you for caring,
Christophe

**Comment by bzg** [comment]
Thank you very much for the quick fix!
