### ISSUE TITLE
OpenSVC support for NFSv4 clustering on RHEL 8.x

### ISSUE THREAD

**Issue by luki009** [opensvc/opensvc#605]
Hi, does opensvc support NFSv4 ? I was not able to find anything in documentation and also went over code but did not find answers.

The RPC services with NFSv4
The mounting and locking protocols have been incorporated into the NFSv4 protocol. The server also listens on the well-known TCP port 2049. As such, NFSv4 does not need to interact with rpcbind, lockd, and rpc-statd services. The nfs-mountd service is still required on the NFS server to set up the exports, but is not involved in any over-the-wire operations.

**Comment by cvaroqui** [comment]
Hello,

opensvc is indeed well suited to handle failover of user-land process, and has been used for ha-nfs already.
That said, we at opensvc, have not configured that kind of svc these last few years. So we would be interested in sharing our opensvc skills and your nfs skills on a common test cluster we would provide.
If you are interested in this small interesting joint venture, just send me privately your email address and we will invite you to https://meet.opensvc.com to collaborate live.

Thank you for your interest in our project.

**Comment by luki009** [comment]
Hello,
thank you for offer but I am afraid that I don't have that level of knowledge regarding NFS. I just follow Rhel documentation and tried to build couple of VMs to test opensvc and NFS clustering. Simple NFSv4 for testing can be built for example based on this guide https://computingforgeeks.com/install-and-configure-nfs-server-on-centos-rhel/ ,on RHEL 8 it is default version of nfs. If i will move forward with my test solution I will definitely update you with results. 
Or if you will have some new findings regarding this I will appreciate also update in this thread.

**Comment by cvaroqui** [comment]
We decided to refresh our svc template for this use-case anyway.
We already have a prototype using drbd as the storage replication layer (replaceable if you have something else at hand, like SAN disks).

The documentation is being updated now, and we will soon post a link to a draft so you can test and comment.

**Comment by luki009** [comment]
Thank you, I appreciate your effort and waiting for link to documentation draft.

**Comment by cvaroqui** [comment]
Please find the link to the HOWTO we prepared for the NFS4 HA failover service.
https://docs.opensvc.com/latest/howto.nfs4ha.trad.html

This setup does not use any fancy, hard to diagnose tech like persistent volumes, backend networks, ingress gateway, etc... It's meant to be robust and easy to troubleshoot for admins. I understood this should matches your expectations.

We very much would like your feedback on this HOWTO.
You can send here or in a meet.opensvc.com chat room we will create when you register there.

Thanks in advance.
Christophe.

**Comment by arnaudveron** [comment]
Hi

We have just published a new HOWTO describing the same NFS V4 HA failover service, but integrated with containers.
It has been tested on RHEL 8.7 with podman, but it should also work with docker on other distros.

https://docs.opensvc.com/latest/howto.nfs4ha.cont.html

Arnaud

**Comment by luki009** [comment]
Hi,
I did follow published documentation but I encountered few problems:
1. After masking of all mentioned processes, test/svc/nfsv4 will fail to start with error:
![image](https://user-images.githubusercontent.com/8204290/224058511-41f5e2f6-dedb-4078-8fd4-961ea05d01f3.png)
Solution for this is to either unmask rpcbind.service and rpcbind.socket and leave them running or to define another app in config to start rpcbind as:
[app#x]
type=simple
start=/usr/bin/rpcbind -w -f
I did place this definition before [app#3] in config

With this workaround i managed to finish rest of steps but  in the end I was not able to mount nfs.
[root@node2 lukas]# mount  vip:/ ./nfsmount
mount.nfs: access denied by server while mounting vip:/

Everything seems to be running, i don't see any errors in logs.. just nfs share is not exported which confirms also 
[root@node1 etc]# showmount --exports
Export list for node1:
[root@node1 etc]# 

om status: 
[root@node1 etc]# om mon
Threads                                node1        node2       
 daemon         running              |                          
 hb#1.rx        running   [::]:10000 | /            O           
 hb#1.tx        running              | /            O           
 listener       running 0.0.0.0:1214
 monitor        running             
 scheduler      running             

Nodes                                  node1        node2       
 score                               | 93           90          
  load 15m                           | 0.1          0.1         
  mem                                | 45/98%:3.64g 58/98%:1.77g
  swap                               | 0/90%:1.57g  6/90%:1.57g 
 state                               |                          

*/svc/*                                node1        node2       
 test/svc/nfsv4 up       ha    1/1   | O^           S           

[root@node1 etc]# om test/svc/nfsv4 print status -r
test/svc/nfsv4                   up                                                           
`- instances            
   |- node2                      stdby up   idle                            
   `- node1                      up         idle, started 
      |- ip#1           ........ up         192.168.0.155/255.255.255.0 enp0s3 vip            
      |- disk#1         ......S. stdby up   lv vg2/nfsv4.test.svc.cluster1                    
      |- disk#2         ......S. stdby up   drbd nfsv4.test.svc.cluster1                      
      |                                     info: Primary                                     
      |- fs#1           ........ up         xfs /dev/drbd0@/srv/nfsv4.test.svc.cluster1       
      |- app#1          ...../.. up         simple: nfsdcld                                   
      |- app#2          ...../.. up         simple: rpc.idmapd                                
      |- app#3          ...../.. up         forking: rpc.nfsd                                 
      |- app#4          ...../.. up         simple: rpc.mountd                                
      `- sync#i0        ..DO./.. n/a        rsync svc config to nodes

**Comment by arnaudveron** [comment]
I'm surprised because rpcbind is not needed for nfsv4.
Do you mind sending your nfs.conf and exports file to support@opensvc.com please ?

**Comment by luki009** [comment]
Hi, I am also surprised with that situation.

After deeper investigation now I found reason of problems.
Looks like after initial setup on step Enable & start OpenSVC app resources
https://docs.opensvc.com/latest/howto.nfs4ha.trad.html#enable-start-opensvc-app-resources

command `om test/svc/nfsv4 start --rid app` did not managed to get control over system services and all apps resources were still running under systemd therefore opensvc did not manage to export shares and would throw also error regarding rpcbind.service.

Situation was resolved with running `om test/svc/nfsv4 stop --rid app` which would kill running systemd services and then run `om test/svc/nfsv4 start --rid app` again

What I did not realize is that based on documentation I did mask systemd service but those services were never stopped which blocked opensvc to gain control. 
Therefore I suggest to add to documentation before masking services step  to run:
`systemctl stop rpc-statd.service rpcbind.service rpcbind.socket nfs-server.service nfs-mountd.service nfs-idmapd.service nfsdcld.service` or to run `om test/svc/nfsv4 stop --rid app` before start OpenSVC app resources. Rpcbind is indeed not needed.

After I got cluster to work, performed some tests as switching during continuous read and write operation and it really works great and it switched without problems. You did great job with opensvc guys. Huge thank you for your effort to create guide for NFSv4 it really helped.

**Comment by arnaudveron** [comment]
Hi

Great ! Thank you for letting us know about this resolution.

I think you may have missed the `--now` option while running the [systemctl mask](https://docs.opensvc.com/latest/howto.nfs4ha.trad.html#disable-nfs4-related-systemd-unit-files) command.
It should stop the units, and mask them, to make sure that only opensvc is dealing with the nfs stack.

**Comment by luki009** [comment]
Hi,
Well I did not miss --now part. I executed it with --now but really have o idea what happened. But definitely `om test/svc/nfsv4 stop --rid app`  is resolving issue.
