### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by woodholly** [opensvc/opensvc#653]
1) Bug in https://docs.opensvc.com/2.1/howto.getting.started.html#cluster-build
```
om cluster set --param hb#1.type --value unicast
om mon
```
Shows hb status, but in reality hb does not show up in om mon until other node joins the cluster.

2) https://docs.opensvc.com/2.1/howto.getting.started.html#application-integration mongoose binary mentioned in the docs is outdated for modern os and fails to start with crash dump :)

**Comment by cvaroqui** [comment]
https://github.com/opensvc/docs.opensvc.com/commit/ec4916829767ffb25372fa8d87dbd61c5eb01a8c fixes the first sub-issue. Thank you for reporting this error.

We will look into using another server than mongoose in the app resource tutorial. It will take about 2 weeks to redo this doc properly. Thanks for caring.

**Comment by woodholly** [comment]
Good! New findings:
Screencast at 24:53 mentions "/data/opensvc/templates/odns.conf" template which is not available in deb package.
Same at 27:32 with envoy.xds.yaml
Ah, I see where it came from - https://github.com/opensvc/opensvc_templates, shouldn't it be a part of the installation package ?

**Comment by arnaudveron** [comment]
Hi,
We got rid of mongoose in the app resource, [document](https://docs.opensvc.com/latest/howto.getting.started.html) is now updated.
We prefer os package to be shipped without templates, you have found the correct repository for examples.
Thanks for your comments.
